# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='inversion/comprobantes/%Y/%m/%d/')),
                ('status', models.CharField(default='Por Pagar', max_length=20)),
                ('devolucion', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('porcentaje_pagado', models.IntegerField(default=0)),
                ('cantidad_a_deber', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tipo', models.CharField(choices=[('Pago de Interés', 'Pago de interés'), ('Pago de Inversión', 'Pago de Inversión')], max_length=30)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pago/comprobantes/%Y/%m/%d/')),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.Inversion')),
            ],
        ),
    ]
