# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('Pago de Interés', 'Pago de interés'), ('Pago de cantidad invertida', 'Pago de cantidad invertida')], max_length=30),
        ),
    ]
