# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0002_auto_20170103_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/'),
        ),
    ]
