# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0005_auto_20170103_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='status',
            field=models.CharField(default='En Proceso', max_length=20),
        ),
    ]
