# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0006_inversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='devolucion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='status',
            field=models.CharField(default='Por Pagar', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('Pago de Interés', 'Pago de interés'), ('Pago de Inversión', 'Pago de Inversión')], max_length=30),
        ),
    ]
