# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0007_auto_20170110_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='porcentajepagado',
            field=models.IntegerField(default=0),
        ),
    ]
