# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0008_inversion_porcentajepagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversion',
            old_name='porcentajepagado',
            new_name='porcentaje_pagado',
        ),
    ]
