# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0009_auto_20170110_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='cantidad_a_deber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
