# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0010_inversion_cantidad_a_deber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='inversion/comprobantes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='pago/comprobantes/%Y/%m/%d/'),
        ),
    ]
